language: go

go:
  - 1.14.x

env:
  - GO111MODULE=on AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

before_install:
  - go get -v golang.org/x/lint/golint

script:
  - go test -cpu=1,2  -race -count 100 ./...