dist: bionic

language: go

go:
  - 1.14.x

env:
  - GO111MODULE=on

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.25.1
script:
  - golangci-lint run
  - go test -v -race ./...